services:

  kafka:
    ports:
      - "9092:9092"

  postgres:
    ports:
      - "5432:5432"

  app:
    ports:
      - "8080:8080"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
